#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build.py -- turns workout/src/ into the deployable files in workout/.

    python build.py                 build once
    python build.py --serve         build, then serve on http://localhost:8765
    python build.py --watch         rebuild whenever a source file changes
    python build.py --clean         delete the built files

Stdlib only.  There is no Node on this machine and this app should not need a
toolchain to survive, so the bundler below is ~120 lines and handles exactly the
ES-module subset src/js uses:

    import { a, b as c } from './x.js';
    import * as ns from './x.js';
    export function f() {}   export const x =   export let x =   export class X

No default exports, no re-exports, no circular imports.  A violation is a build
error with a pointer to the file, never a silently broken bundle.

What the build actually does for you -- the reason this is not just a folder of
files you edit in place:

  1. Bundles src/js/*.js into one app.js, so the service worker has one script
     to cache instead of a dozen, and Safari makes one request.
  2. Synthesises two generated modules:
       generated/seed.js   -- src/data/seed.json as a JS constant
       generated/build.js  -- version + timestamp, shown on the Export screen
  3. Inlines styles.css into index.html (no flash of unstyled content offline).
  4. Hashes every built asset and stamps that hash into the service worker's
     cache name and precache list, so deploying a change always busts the cache
     and you never have to remember to bump a version by hand.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
OUT = ROOT
ENTRY = SRC / "js" / "app.js"

# Files the build owns in OUT. --clean removes exactly these.
BUILT = ["index.html", "app.js", "sw.js", "manifest.webmanifest", "icons"]


# ===========================================================================
# Bundler
# ===========================================================================

IMPORT_RE = re.compile(
    r"^[ \t]*import\s+(?P<clause>[^;]+?)\s+from\s+['\"](?P<path>[^'\"]+)['\"]\s*;[ \t]*\r?\n?",
    re.MULTILINE | re.DOTALL,
)
BARE_IMPORT_RE = re.compile(r"^[ \t]*import\s+['\"][^'\"]+['\"]\s*;[ \t]*\r?\n?", re.MULTILINE)
EXPORT_NAME_RES = [
    re.compile(r"^export\s+(?:async\s+)?function\s+([A-Za-z_$][\w$]*)", re.MULTILINE),
    re.compile(r"^export\s+(?:const|let|var)\s+([A-Za-z_$][\w$]*)", re.MULTILINE),
    re.compile(r"^export\s+class\s+([A-Za-z_$][\w$]*)", re.MULTILINE),
]
EXPORT_STRIP_RE = re.compile(
    r"^export\s+(?=(?:async\s+)?function\b|const\b|let\b|var\b|class\b)", re.MULTILINE
)
BAD_EXPORT_RE = re.compile(r"^export\s+(?:default\b|\{)", re.MULTILINE)


class BuildError(Exception):
    pass


class Module:
    def __init__(self, key: str, source: str, origin: str):
        self.key = key
        self.origin = origin
        self.source = source
        self.imports: list[tuple[str, str]] = []   # (clause, resolved key)
        self.exports: list[str] = []
        self.body = ""


def module_key(path: Path) -> str:
    try:
        return path.relative_to(SRC).as_posix()
    except ValueError:
        return path.as_posix()


def generated_source(key: str) -> str | None:
    """Virtual modules -- data that belongs in the bundle but not in git twice."""
    if key == "js/generated/seed.js":
        seed_path = SRC / "data" / "seed.json"
        if not seed_path.exists():
            raise BuildError(
                "src/data/seed.json is missing.  Run:  python tools/make_seed.py"
            )
        data = json.loads(seed_path.read_text(encoding="utf-8"))
        return (
            "// GENERATED by build.py from src/data/seed.json -- do not edit.\n"
            "export const SEED = "
            + json.dumps(data, ensure_ascii=False, separators=(",", ":"))
            + ";\n"
        )
    if key == "js/generated/build.js":
        return (
            "// GENERATED by build.py -- do not edit.\n"
            "export const BUILD = " + json.dumps(BUILD_INFO, separators=(",", ":")) + ";\n"
        )
    return None


def resolve(importer_key: str, spec: str) -> str:
    if not spec.startswith("."):
        raise BuildError(
            f"{importer_key}: bare import {spec!r}. This bundler only does relative paths."
        )
    base = Path(importer_key).parent
    return (base / spec).as_posix().replace("/./", "/")


def normalise(key: str) -> str:
    parts: list[str] = []
    for p in key.split("/"):
        if p == "." or p == "":
            continue
        if p == "..":
            if parts:
                parts.pop()
            continue
        parts.append(p)
    return "/".join(parts)


def load_module(key: str, modules: dict[str, Module]) -> Module:
    key = normalise(key)
    if key in modules:
        return modules[key]

    gen = generated_source(key)
    if gen is not None:
        source, origin = gen, "(generated)"
    else:
        path = SRC / key
        if not path.exists():
            raise BuildError(f"module not found: {key}")
        source, origin = path.read_text(encoding="utf-8"), str(path.relative_to(ROOT))

    bad = BAD_EXPORT_RE.search(source)
    if bad:
        line = source[: bad.start()].count("\n") + 1
        raise BuildError(
            f"{origin}:{line}: 'export default' and 'export {{ ... }}' are not supported.\n"
            "  Use 'export function/const/let/class' on the declaration itself."
        )

    mod = Module(key, source, origin)
    modules[key] = mod

    for m in IMPORT_RE.finditer(source):
        dep = normalise(resolve(key, m.group("path")))
        mod.imports.append((m.group("clause").strip(), dep))

    for rx in EXPORT_NAME_RES:
        mod.exports.extend(rx.findall(source))

    body = IMPORT_RE.sub("", source)
    body = BARE_IMPORT_RE.sub("", body)
    mod.body = EXPORT_STRIP_RE.sub("", body)

    for _clause, dep in mod.imports:
        load_module(dep, modules)
    return mod


def order(modules: dict[str, Module], entry: str) -> list[str]:
    seen: dict[str, int] = {}   # 0 = visiting, 1 = done
    out: list[str] = []
    stack: list[str] = []

    def visit(k: str):
        state = seen.get(k)
        if state == 1:
            return
        if state == 0:
            cycle = " -> ".join(stack[stack.index(k):] + [k])
            raise BuildError(f"circular import: {cycle}")
        seen[k] = 0
        stack.append(k)
        for _clause, dep in modules[k].imports:
            visit(dep)
        stack.pop()
        seen[k] = 1
        out.append(k)

    visit(entry)
    return out


def clause_to_binding(clause: str, dep_var: str, origin: str) -> str:
    clause = clause.strip()
    if clause.startswith("*"):
        m = re.match(r"\*\s+as\s+([A-Za-z_$][\w$]*)$", clause)
        if not m:
            raise BuildError(f"{origin}: cannot parse import clause {clause!r}")
        return f"  var {m.group(1)} = {dep_var};"
    if clause.startswith("{"):
        inner = clause.strip()[1:-1]
        names = []
        for piece in inner.split(","):
            piece = piece.strip()
            if not piece:
                continue
            m = re.match(r"^([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?$", piece)
            if not m:
                raise BuildError(f"{origin}: cannot parse imported name {piece!r}")
            names.append(f"{m.group(1)}: {m.group(2)}" if m.group(2) else m.group(1))
        return "  var { " + ", ".join(names) + " } = " + dep_var + ";"
    raise BuildError(
        f"{origin}: default imports are not supported ({clause!r}). Use named imports."
    )


def var_for(key: str) -> str:
    return "__m_" + re.sub(r"[^A-Za-z0-9]", "_", key)


def bundle() -> str:
    modules: dict[str, Module] = {}
    entry_key = module_key(ENTRY)
    load_module(entry_key, modules)
    keys = order(modules, entry_key)

    chunks = [
        "/* Workout Tracker -- bundled by build.py. Edit src/, not this file. */",
        "(function () {",
        '"use strict";',
    ]
    for k in keys:
        mod = modules[k]
        chunks.append(f"\n/* ---- {k} ---- */")
        chunks.append(f"var {var_for(k)} = (function () {{")
        for clause, dep in mod.imports:
            chunks.append(clause_to_binding(clause, var_for(dep), mod.origin))
        chunks.append(mod.body.rstrip())
        if mod.exports:
            pairs = ", ".join(f"{n}: {n}" for n in dict.fromkeys(mod.exports))
            chunks.append("  return { " + pairs + " };")
        else:
            chunks.append("  return {};")
        chunks.append("})();")
    chunks.append(f"\nvoid {var_for(entry_key)};")
    chunks.append("})();")
    return "\n".join(chunks) + "\n"


# ===========================================================================
# Assets
# ===========================================================================

BUILD_INFO: dict = {}


def sha(data: bytes, n: int = 10) -> str:
    return hashlib.sha256(data).hexdigest()[:n]


def human(n: int) -> str:
    return f"{n / 1024:.1f} KB" if n >= 1024 else f"{n} B"


def build(verbose: bool = True) -> dict:
    if not SRC.exists():
        raise BuildError(f"no src/ directory at {SRC}")

    stamp = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
    BUILD_INFO.clear()
    BUILD_INFO.update({"version": "pending", "builtAt": stamp})

    # 1. JS bundle, built twice.  The first pass hashes the code with the
    #    build stamp blanked out, so the version depends only on the source --
    #    rebuilding unchanged sources gives the same version, and the service
    #    worker does not churn a new cache every time you run the build.
    BUILD_INFO.update({"version": "0" * 10, "builtAt": ""})
    version = sha(bundle().encode("utf-8"))
    BUILD_INFO.update({"version": version, "builtAt": stamp})
    js = bundle()

    # 2. HTML with the stylesheet inlined.
    css = (SRC / "styles.css").read_text(encoding="utf-8")
    html = (SRC / "index.html").read_text(encoding="utf-8")
    if "/*@STYLES*/" not in html:
        raise BuildError("src/index.html lost its /*@STYLES*/ placeholder")
    html = html.replace("/*@STYLES*/", "\n" + css.strip() + "\n")
    html = html.replace("/*@VERSION*/", version)

    # 3. Static assets.
    OUT.mkdir(parents=True, exist_ok=True)
    icons_out = OUT / "icons"
    icons_out.mkdir(parents=True, exist_ok=True)
    # Copy file-by-file rather than rmtree+copytree: OneDrive holds a handle on
    # the directory often enough that removing it fails with WinError 5.
    wanted = {p.name for p in (SRC / "icons").iterdir() if p.is_file()}
    for p in (SRC / "icons").iterdir():
        if p.is_file():
            shutil.copyfile(p, icons_out / p.name)
    for p in icons_out.iterdir():
        if p.is_file() and p.name not in wanted:
            p.unlink()
    manifest = (SRC / "manifest.webmanifest").read_text(encoding="utf-8")

    written: dict[str, int] = {}

    def write(rel: str, text: str):
        p = OUT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8", newline="\n")
        written[rel] = len(text.encode("utf-8"))

    write("index.html", html)
    write("app.js", js)
    write("manifest.webmanifest", manifest)

    # 4. Service worker -- precache list + a cache name hashed over every asset.
    precache = ["./", "./index.html", "./app.js", "./manifest.webmanifest"]
    for icon in sorted(icons_out.iterdir()):
        precache.append("./icons/" + icon.name)

    # The cache name hashes the *content* -- the JS version (itself content-only)
    # plus every other asset -- and deliberately not the build timestamp, so
    # re-running the build without editing anything does not invalidate the
    # cache already sitting on the phone.
    sw_template = (SRC / "sw.js").read_text(encoding="utf-8")
    digest = hashlib.sha256()
    for text in (version, css, manifest, sw_template, json.dumps(precache)):
        digest.update(text.encode("utf-8"))
    for icon in sorted(icons_out.iterdir()):
        digest.update(icon.read_bytes())
    cache_name = "workout-" + digest.hexdigest()[:12]

    sw = sw_template.replace("/*@CACHE_NAME*/", cache_name)
    sw = sw.replace("/*@PRECACHE*/", json.dumps(precache, indent=2))
    write("sw.js", sw)

    for icon in sorted(icons_out.iterdir()):
        written["icons/" + icon.name] = icon.stat().st_size

    if verbose:
        print(f"\nbuild {version}  cache {cache_name}  {stamp}")
        total = 0
        for rel, size in written.items():
            total += size
            print(f"  {rel:28s} {human(size):>10s}")
        print(f"  {'total':28s} {human(total):>10s}")
        print(f"\n  output: {OUT}")
    return {"version": version, "cache": cache_name, "files": written}


def clean():
    for rel in BUILT:
        p = OUT / rel
        if p.is_dir():
            # Files first, then the directory -- and shrug if OneDrive is
            # holding the directory handle (WinError 5), which it often is.
            for child in p.rglob("*"):
                if child.is_file():
                    child.unlink()
            try:
                shutil.rmtree(p)
            except OSError as err:
                print(f"emptied {rel}/ (could not remove the folder: {err.strerror})")
            else:
                print("removed", rel + "/")
        elif p.exists():
            p.unlink()
            print("removed", rel)


# ===========================================================================
# Dev server / watch
# ===========================================================================

def sources() -> list[Path]:
    out = [p for p in SRC.rglob("*") if p.is_file()]
    return sorted(out)


def fingerprint() -> tuple:
    return tuple((str(p), p.stat().st_mtime_ns) for p in sources())


def watch():
    print("watching src/ ... Ctrl-C to stop")
    last = None
    while True:
        fp = fingerprint()
        if fp != last:
            last = fp
            try:
                build()
            except BuildError as err:
                print(f"\nBUILD FAILED: {err}\n", file=sys.stderr)
            except Exception as err:  # noqa: BLE001
                print(f"\nBUILD FAILED: {err!r}\n", file=sys.stderr)
        time.sleep(0.6)


def serve(port: int):
    import http.server
    import socketserver

    class Handler(http.server.SimpleHTTPRequestHandler):
        extensions_map = {
            **http.server.SimpleHTTPRequestHandler.extensions_map,
            ".webmanifest": "application/manifest+json",
            ".js": "text/javascript",
            ".json": "application/json",
        }

        def __init__(self, *a, **kw):
            super().__init__(*a, directory=str(OUT), **kw)

        def end_headers(self):
            # A dev server that caches is a dev server that lies.
            self.send_header("Cache-Control", "no-store, max-age=0")
            super().end_headers()

        def log_message(self, fmt, *args):
            sys.stderr.write("  %s\n" % (fmt % args))

    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("127.0.0.1", port), Handler) as httpd:
        print(f"\n  serving {OUT} at http://localhost:{port}/  (Ctrl-C to stop)\n")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nstopped")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--serve", action="store_true", help="build, then serve on --port")
    ap.add_argument("--watch", action="store_true", help="rebuild on change")
    ap.add_argument("--clean", action="store_true", help="delete built files")
    ap.add_argument("--port", type=int, default=8765)
    args = ap.parse_args()

    if args.clean:
        clean()
        return

    try:
        build()
    except BuildError as err:
        print(f"\nBUILD FAILED: {err}\n", file=sys.stderr)
        sys.exit(1)

    if args.watch:
        watch()
    elif args.serve:
        serve(args.port)


if __name__ == "__main__":
    main()
